name: Build with CMake
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        apt update
        apt upgrade -y
        apt install libcurl4-openssl-dev libjpeg-dev libtidy-dev -y
    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/Build
        -DCMAKE_CXX_COMPILER=g++
        -DCMAKE_C_COMPILER=gcc
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/Build --config Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: OJTool
        path: ${{ github.workspace }}/Build/OJTool