name: Build with CMake
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install libpng
    - name: Configure CMake
      run: >
        cmake -B ${{ github.workspace }}/Build
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/Build --config Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: OJTool
        path: ${{ github.workspace }}/Build/OJTool
